[project]
name = "git-wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plumbum>=1.9.0",
    "regex>=2024.11.6",
]
